dana-team/platform-backend

cmd/main.go, src/controllers/namespace.go, src/routes/namespace.go, src/types/namespace.go
Cleanup namespace controller, router and main of it.
=> refactor: cleanup namespace

cmd/main.go, src/controllers/secret.go, src/routes/v1/namespace.go, src/routes/v1/namespace_test.go, src/routes/v1/secret.go, src/routes/v1/secret_test.go, src/routes/v1/setup.go, src/routes/v1/setup_test.go, src/types/secret.go
- Added namespace route tests.
- Added setup unit tests.
- Updated path parameters.
- Updated model types.
=> tests: add namespace route

docs/api/capp.md
=> docs: updated Capp doc file

src/controllers/secret.go, src/routes/v1/namespace.go, src/routes/v1/secret.go, src/routes/v1/secret_test.go, src/types/namespace.go, src/types/secret.go
Add validation of the request parameters in API endpoints, and do slightly refactor of the endpoints to improve code readability.
Issue #13.
=> refactor: validate request parameters

src/controllers/secret.go, src/routes/v1/secret.go, src/routes/v1/secret_test.go, src/types/secret.go
Remove unnecessary model types from Secrets router.
=> refactor: cleanup secret model types

src/controllers/capp.go, src/controllers/capprevision.go, src/controllers/common.go, src/routes/v1/capprevision.go, src/routes/v1/capprevision_test.go, src/routes/v1/setup.go, src/routes/v1/setup_test.go, src/types/capp.go, src/types/capprevision.go, src/types/common.go
Implements a new ContainerApp Revision API based on an updated [capp_revision.md](https://github.com/dana-team/platform-backend/blob/main/docs/api/capp_revision.md) design.
=> feat: implement container app revision api

README.md, src/routes/v1/login.go, src/routes/v1/login_test.go
refactor: pass credentials with basic auth
=> refactor: pass credentials with basic auth

src/controllers/capp.go, src/controllers/secret.go, src/routes/v1/capp.go, src/routes/v1/capp_test.go, src/routes/v1/secret.go, src/routes/v1/secret_test.go, src/routes/v1/setup.go, src/routes/v1/setup_test.go, src/types/capp.go, src/types/secret.go
=> refactor: use update instead of patch

docs/api/capp.md, docs/api/capp_revision.md, docs/api/namespace.md, docs/api/secrets.md, docs/api/users.md
=> design: pagination support

src/routes/v1/capp.go, src/routes/v1/capprevision.go, src/routes/v1/secret.go
Use correctly functions of validating parameters in v1 routes.
=> fix: validate parameters in routes

src/middleware/auth_middleware.go
Declare logger variable to set a logger of the controller-runtime library.
=> fix: declare logger variable

README.md, docs/api/capp.md, docs/api/capp_revision.md, docs/api/configmaps.md, docs/api/containers.md, docs/api/namespace.md, docs/api/token.md, docs/api/users.md
=> docs: cleanup apis

docs/api/configmaps.md, src/controllers/configmaps.go, src/routes/v1/configmaps.go, src/routes/v1/configmaps_test.go, src/routes/v1/setup.go, src/routes/v1/setup_test.go, src/types/configmaps.go
Implements a new ConfigMap API based on a new [configmaps.md](https://github.com/dana-team/platform-backend/blob/main/docs/api/configmaps.md) design.
=> feat: implement config map api

docs/api/capp.md
=> docs: change get capps response

src/auth/openshift.go
=> feat: added debug logs to auth

src/routes/v1/users.go, src/routes/v1/users_test.go, src/types/secret.go, src/types/user.go
added enum validations to types:
- secrets
- users
=> fix: added enum validations to types

src/controllers/capp.go, src/types/capp.go
Implements the controller logic needed to match #58.
=> refactor: change response of get capps route to match docs

src/auth/openshift_test.go
Fixes #22. The HTTP Server in the tests is not initialized for every test case, which fixes the interference between cases that caused the test cases to occasionally fail.
=> fix: interference between cases cause flaky auth test

src/controllers/secret.go, src/routes/v1/secret.go, src/routes/v1/secret_test.go, src/routes/v1/setup_test.go, src/types/secret.go, src/utils/keyvalue.go
=> tests: added secrets unit tests

src/controllers/secret.go, src/utils/keyvalue.go
clean up the secret controller
=> cleanup: clean up the secret controller

src/controllers/users.go, src/routes/mocks/capp.go, src/routes/mocks/user.go, src/routes/v1/capp_test.go, src/routes/v1/capprevision_test.go, src/routes/v1/configmaps_test.go, src/routes/v1/login_test.go, src/routes/v1/namespace_test.go, src/routes/v1/secret_test.go, src/routes/v1/setup_test.go, src/routes/v1/users.go, src/routes/v1/users_test.go, src/types/user.go
This PR makes some changes to the test cases of the user routes and the login routes, and also moves all router test cases to the same package of the routes themselves.
=> tests: modify user and login cases and fix package of test cases

src/routes/v1/capp_test.go, src/routes/v1/capprevision_test.go, src/routes/v1/namespace_test.go, src/routes/v1/secret_test.go, src/routes/v1/setup_test.go, src/routes/v1/users_test.go
refactor: remove redundant  from routes
=> refactor: remove redundant  from routes

src/controllers/namespace_test.go, src/utils/labels.go
added unit tests to the namespace controller
=> tests: added unit tests to the namespace controller

hack/deploy-capp.sh
Needed due to a #184 on container-app-operator
=> ci: change dns configmap name and values

src/controllers/capp.go, src/controllers/capp_test.go, src/routes/v1/capp.go, src/routes/v1/capp_test.go, src/routes/v1/setup.go, src/routes/v1/setup_test.go, src/types/capp.go, src/utils/testutils/consts.go, src/utils/testutils/mocks/adapter.go, src/utils/testutils/mocks/capp.go
added get state route for capp
=> feat: added get state route for capp

src/utils/testutils/mocks/capp.go, test/e2e_tests/capp.go
added e2e tests to edit&get state
=> tests: add e2e tests for edit state and get state routes
